### ISSUE TITLE
Add support for builders

### ISSUE THREAD

**Issue by Araq** [nim-lang/atlas#7]
Atlas currently lacks any support for a "build" step. Ideally the implementation is flexible enough to integrate `cmake` etc.

**Comment by elcritch** [comment]
`cmake` support would be great. It might be trickier to do the dependency mapping, but that belongs in the extractors section it looks like.

cmake generally assumes a `build/` folder and often an `install/` folder. My initial thought would be that cmake would work best with the `env` feature to simplify linking by installing into whatever install folder the `env` feature uses.

For example, building some `foo` project builds a `libfoo.so`. This would be easiest to integrate with existing Nim projects where you specify `dynlib: "libfoo.dll"` without specifying the paths. However, it'd be possible to set the link path and dlpath for every library by modifying the C compiler flags, just really annoying.

**Comment by elcritch** [comment]
The `build` folder is also interesting. It's annoying to dirty the git repos with build artifacts, so supporting a first class concept of build caches would be useful. 

For example, Nim could also use the build cache rather than the current global `~/.cache/nim/`. 

I don't know if this is already a thing yet in atlas, but I thought it'd be good to note it.

**Comment by Araq** [comment]
Has been implemented.
